version: '3'

services:
  web:
    build: .
    environment:
      - BIP39=${BIP39}
      - DATABASE_URL=${DATABASE_URL}
      - DEMO_SERVER=${DEMO_SERVER}
      - HOMEPAGE=${HOMEPAGE}
      - REDIS_HOST=redis
      - SENTRY_DSN=${SENTRY_DSN}
      - SIGNING_SECRET=${SIGNING_SECRET}
      - SLACK_CLIENT_ID=${SLACK_CLIENT_ID}
      - SLACK_CLIENT_SECRET=${SLACK_CLIENT_SECRET}
      - SLACK_SERVER=${SLACK_SERVER}
    restart: unless-stopped
    ports:
     - 8000:8000

  redis:
    image: redis:6-alpine
    restart: unless-stopped
